Silence compile errors with clang 19.0.0git
-Wcast-function-type-mismatch was added in clang 19.1. Change the
version check to "VERSION_GREATER 19.0.999" instead.

Add -Wno-vla-cxx-extension for ihv/arm to silence

  gator_api.cpp:312:15: error: variable length arrays in C++ are a
  Clang extension [-Werror,-Wvla-cxx-extension]